services:
  mongo:
    image: mongo:latest
    container_name: chat-app
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_USERNAME=${DB_USERNAME}
      - MONGO_PASSWORD=${DB_PASSWORD}
    ports:
      - 7777:27017
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
